language: node_js
node_js:
   - "node"
script:
   - node_modules/.bin/jshint src
   - npm test
   - node_modules/.bin/jsdoc src
deploy:
   provider: pages
   github-token: $blank
   skip_cleanup: true
   local-dir: ./out
